unbind r
bind r source-file ~/.tmux.conf

# vim
setw -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

unbind C-`
set-option -g prefix `
bind ` send-prefix

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g mouse on


#theme
set -g @plugin 'o0th/tmux-nova'
set -g @nova-nerdfonts true

set -g @nova-segment-mode "#S #{?client_prefix, , } "
set -g @nova-segment-mode-colors " #20192b  #6d61a8"

set -g @nova-pane "#I#{?pane_in_mode,| #{pane_mode},}  #W"
set -g @nova-pane-active-border-style "#252525"
set -g @nova-pane-border-style "#252525"

set -g @nova-status-style-bg "#20192b"
set -g @nova-status-style-fg "#6d61a8"
set -g @nova-status-style-active-bg "#20192b"
set -g @nova-status-style-active-fg "#e8e5cf"

set -g @nova-rows 0


run '~/.tmux/plugins/tpm/tpm'

