shell=/usr/bin/zsh

[main]
font = SauceCodePro Nerd Font:size=12
include=/home/arjun/.config/foot/tokio-dark-nights-tweaked
pad=5x5x5x5

[bell]
system=no

[key-bindings]
clipboard-paste=Control+v XF86Paste

[text-bindings]
# Delete whole word (ctrl+w)
\x17=Control+BackSpace
# bind ctrl+v control character to ctrl+shift+v
\x16=Control+Shift+v



